apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-config
  namespace: enterprise-platform
data:
  SPRING_PROFILES_ACTIVE: "docker"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://service-discovery:8761/eureka"
  CONFIG_SERVER_URL: "http://config-server:8888"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  SPRING_DATA_REDIS_HOST: "redis"
  SPRING_DATA_REDIS_PORT: "6379"
  LOGGING_LEVEL_ROOT: "INFO"
  LOGGING_LEVEL_APP: "INFO"
